/**
 * Canonical industry list for NTS Claims Tracker.
 * Used in CustomerFormModal (searchable combobox) and any future industry selectors.
 * Add new entries in alphabetical order. The DB stores raw strings so these are
 * just suggestions — the combobox also accepts freeform input for legacy values.
 */
export const INDUSTRIES: string[] = [
  "Aerospace & Defense",
  "Agriculture & Farming",
  "Agriculture Equipment",
  "Asphalt & Paving",
  "Automotive & Vehicles",
  "Automotive Manufacturing",
  "Boat & Marine Manufacturing",
  "Broadcasting & Media Equipment",
  "Bulk Liquid Transport",
  "Chemicals & Petrochemicals",
  "Concrete & Masonry",
  "Construction & Development",
  "Crane & Rigging Services",
  "Demolition & Excavation",
  "Distribution & Fulfillment",
  "Education & Universities",
  "Electrical & Power Distribution",
  "Electronics & Semiconductors",
  "Energy - Nuclear",
  "Energy - Oil & Gas",
  "Energy - Renewables (Wind / Solar)",
  "Energy - Utilities & Power",
  "Environmental Services",
  "Event, Trade Show & Entertainment",
  "Explosives & Ammunition",
  "Food & Beverage Processing",
  "Forestry & Lumber",
  "Government & Public Sector",
  "Healthcare & Medical Equipment",
  "Heavy Equipment Dealers & Rentals",
  "Heavy Machinery & Industrial",
  "Industrial & Manufacturing",
  "Infrastructure & Civil Engineering",
  "Landscaping & Nursery",
  "Logistics, Warehousing & 3PL",
  "Military & Defense Contractors",
  "Mining & Quarrying",
  "Modular & Prefab Buildings",
  "Oil Field Equipment & Services",
  "Paper, Printing & Packaging",
  "Personal / Individual",
  "Pipeline & Water Infrastructure",
  "Plastics & Rubber",
  "Ports, Rail & Intermodal",
  "Precast Concrete",
  "Public Utilities",
  "Pumps & Industrial Equipment",
  "Real Estate & Property Development",
  "Recycling & Scrap Metal",
  "Retail & E-commerce Distribution",
  "Steel & Metal Products",
  "Stone, Granite & Aggregates",
  "Technology & Telecom",
  "Telecommunications Infrastructure",
  "Textiles & Apparel",
  "Towing & Recovery",
  "Trailers & Specialty Vehicles",
  "Waste Management",
  "Water Treatment & Wastewater",
  "Other",
];
