-- Add profile_slug to brokers for public-facing landing pages (/rep/[slug])
-- Also ensures phone is present (it already is, this is a no-op guard).

ALTER TABLE brokers
  ADD COLUMN IF NOT EXISTS profile_slug text UNIQUE;

-- Auto-generate a slug from first_name + last_name for all existing brokers.
-- Format: "adam-noah", "adam-blanco-2" if collision, etc.
-- New brokers get their slug generated by the app on first save.
DO $$
DECLARE
  rec RECORD;
  base_slug text;
  candidate text;
  counter int;
BEGIN
  FOR rec IN
    SELECT id, first_name, last_name
    FROM brokers
    WHERE profile_slug IS NULL
      AND first_name IS NOT NULL
  LOOP
    base_slug := regexp_replace(
      lower(coalesce(rec.first_name, '') || '-' || coalesce(rec.last_name, '')),
      '[^a-z0-9]+', '-', 'g'
    );
    base_slug := trim(both '-' from base_slug);

    candidate := base_slug;
    counter   := 2;

    WHILE EXISTS (SELECT 1 FROM brokers WHERE profile_slug = candidate AND id <> rec.id) LOOP
      candidate := base_slug || '-' || counter;
      counter   := counter + 1;
    END LOOP;

    UPDATE brokers SET profile_slug = candidate WHERE id = rec.id;
  END LOOP;
END $$;

COMMENT ON COLUMN brokers.profile_slug IS
  'URL-safe slug used for public broker landing pages at /rep/[slug]. Unique, editable by the broker.';
